name: Test
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
  workflow_dispatch:
jobs: 
  Test:
    runs-on: windows_latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with: 
            java-version: 11
            distribution: "temurin"
            architecture: "x64"
      - name: Run the Maven verify phase
        run: mvn clean install
      - name: Run Tests
        run: mvn test
            
      
      
  




    
